camera0: 6
camera1: 12
frame_width: 1920
frame_height: 1080
mono_calibration_frames: 4
stereo_calibration_frames: 4
view_resize: 2
checkerboard_box_size_scale : 1.90
checkerboard_rows: 9
checkerboard_columns: 13
cooldown: 100
